### ISSUE TITLE
NoMatch text not centered in stacked view

### ISSUE THREAD

**Issue by DCsunset** [gregnb/mui-datatables#1695]
## Expected Behavior

The noMatch text should be centered in the stacked view.

## Current Behavior

The noMatch text is not centered in the stacked view.

## Steps to Reproduce (for bugs)

1. Clear all records in the data table.
2. Make the display area small enough to toggle the stacked view.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.11.3     |
| MUI-datatables  |    3.7.7     |
| React        |   17.0.2      |
| browser      |   Firefox, Chrome      |
| etc          |         |

**Comment by TBenton-eb** [comment]
![Screen Shot 2022-07-11 at 3 43 47 PM](https://user-images.githubusercontent.com/88386722/178354786-c9fc8074-0ec1-4f2b-b723-410ddcf6e437.png)
![Screen Shot 2022-07-11 at 3 43 52 PM](https://user-images.githubusercontent.com/88386722/178354800-054215a1-b0c5-41ac-9a73-e03aade1e4d0.png)


This is still an issue.

**Comment by vittxr** [comment]
I override the default css. Its works, but is a tricky.

```css
.tss-1qtl85h-MUIDataTableBodyCell-root.datatables-noprint {
    width: 0 !important;
    display: flex !important;
    justify-content: center !important;
    align-items: center !important;
    margin: auto;
    position: relative;
}

.tss-1qjwhn0-MUIDataTableBody-emptyTitle {
    position: fixed;
    left: 0px;
    right: 0;
    margin: 0 auto;
}
```

It won't work if you have other elements on the sides (right or left) because the `position: fixed` property aligns the element to the viewport. You will need to add some media queries then.
