### ISSUE TITLE
Override MUIDatatable-responsibeBase

### ISSUE THREAD

**Issue by ShedrackGodson** [gregnb/mui-datatables#1944]
I need help on how to override the default style of the div tag just before the table tag to set overflow to none instead of auto. The div has a class of MUIDatatable-responsiveBase.

| Tech         | Version |
|--------------|---------|
| Material-UI Core|  4.12.4    |
| MUI-datatables  |   4.2.2      |
| React        |    17.0.1     |
| browser      |   Chrome, Firefox, Opera      |

**Comment by danieladugyan** [comment]
I encountered the same problem, although I wanted to set it to `overflow: 'visible'`. This did the trick.
```js
const theme = createMuiTheme({
  components: {
    MUIDataTable: {
      styleOverrides: {
        responsiveBase: {
          overflow: 'none',
        },
      },
    },
  },
});
```
```jsx
<MuiThemeProvider theme={theme}>
  // your app
</MuiThemeProvider>
```

**Comment by ShedrackGodson** [comment]
Thanks for the reply,
I defined my theme as
```javascript
const customTheme = createTheme({
    components: {
        MUIDataTable: {
            styleOverrides: {
                responsiveBase: {
                    overflow: 'none',
                },
            },
        }
    }
});

```
but it still overflow, when I inspect the elements I see this CSS style

```css
.tss-eyk1ae-MUIDataTable-responsiveBase.tss-eyk1ae-MUIDataTable-responsiveBase {
    overflow: none; /** this is stroke with the caution that it is invalid property value **/
}
```
and also there is that default style
```css
.tss-eyk1ae-MUIDataTable-responsiveBase {
    overflow: auto;
}
```

where am I getting wrong, any help will be appreciated, Thanks
